repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort --settings-file ./weather_bot/.isort.cfg .
        language: system
        types: [ python ]
        pass_filenames: false
  
      - id: black
        name: black
        entry: black --config ./weather_bot/.black .
        language: system
        types: [ python ]
        pass_filenames: false

      - id: flake8
        name: flake8
        entry: flake8 --config ./weather_bot/.flake8 .
        language: system
        types: [ python ]
        pass_filenames: false